INSERT INTO metastore.data_mart (id, name, case_sensitive_name, description, fk_organisation_id) VALUES ('1570269', 'ORDER_DATA_MART', 'order_data_mart', NULL, '1568338');
INSERT INTO metastore.data_mart_coordinates (id, coordinates, fk_data_mart_id) VALUES ('86050318-1967-4979-8d5e-965ab71a9e29', '[{"tableName":"MY_TEST_DB.ORDERS_ORDER","xCoord":"7px","yCoord":"73px","isExpand":true},{"tableName":"MY_TEST_DB.PRODUCT_CATALOG","xCoord":"405px","yCoord":"76px","isExpand":true},{"tableName":"MY_TEST_DB.ORDER_SHIPMENT","xCoord":"880px","yCoord":"94px","isExpand":true}]', '1570269');
INSERT INTO metastore.data_mart_table (id, name, case_sensitive_name, source_table, fk_data_mart_id) VALUES ('1570270', 'ORDERS_ORDER_NEW', 'orders_order_new', '`my_test_db`.`orders_order`', '1570269');
INSERT INTO metastore.data_mart_table (id, name, case_sensitive_name, source_table, fk_data_mart_id) VALUES ('1570300', 'PRODUCT_CATALOG_NEW', 'product_catalog_new', '`my_test_db`.`product_catalog`', '1570269');
INSERT INTO metastore.data_mart_table (id, name, case_sensitive_name, source_table, fk_data_mart_id) VALUES ('1570309', 'ORDER_SHIPMENT_NEW', 'order_shipment_new', '`my_test_db`.`order_shipment`', '1570269');
INSERT INTO metastore.data_mart_table_schema (id, real_column_name, virtual_name, fk_data_mart_table_id) VALUES ('1570764', 'sku', 'sku', '1570300');
INSERT INTO metastore.data_mart_table_schema (id, real_column_name, virtual_name, fk_data_mart_table_id) VALUES ('1570765', 'sku_type', 'sku_type', '1570300');
INSERT INTO metastore.data_mart_table_schema (id, real_column_name, virtual_name, fk_data_mart_table_id) VALUES ('1570766', 'brand_type', 'brand_type', '1570300');
INSERT INTO metastore.data_mart_table_schema (id, real_column_name, virtual_name, fk_data_mart_table_id) VALUES ('1570767', 'brand', 'brand', '1570300');
INSERT INTO metastore.data_mart_table_schema (id, real_column_name, virtual_name, fk_data_mart_table_id) VALUES ('1570768', 'leaf_category', 'leaf_category', '1570300');
INSERT INTO metastore.data_mart_table_schema (id, real_column_name, virtual_name, fk_data_mart_table_id) VALUES ('1570769', 'category', 'category', '1570300');
INSERT INTO metastore.data_mart_table_schema (id, real_column_name, virtual_name, fk_data_mart_table_id) VALUES ('1570770', 'C1_Category', 'C1_Category', '1570300');
INSERT INTO metastore.data_mart_table_schema (id, real_column_name, virtual_name, fk_data_mart_table_id) VALUES ('1570771', 'stock_status', 'stock_status', '1570300');
INSERT INTO metastore.data_mart_table_schema (id, real_column_name, virtual_name, fk_data_mart_table_id) VALUES ('1570772', 'order_no', 'order_no', '1570309');
INSERT INTO metastore.data_mart_table_schema (id, real_column_name, virtual_name, fk_data_mart_table_id) VALUES ('1570773', 'tax_exclusive_price', 'tax_exclusive_price', '1570309');
INSERT INTO metastore.data_mart_table_schema (id, real_column_name, virtual_name, fk_data_mart_table_id) VALUES ('1570774', 'allocation_mode', 'allocation_mode', '1570309');
INSERT INTO metastore.data_mart_table_schema (id, real_column_name, virtual_name, fk_data_mart_table_id) VALUES ('1570775', 'warehouse_code', 'warehouse_code', '1570309');
INSERT INTO metastore.data_mart_table_schema (id, real_column_name, virtual_name, fk_data_mart_table_id) VALUES ('1570776', 'order_check_gstin', 'order_check_gstin', '1570309');
INSERT INTO metastore.data_mart_table_schema (id, real_column_name, virtual_name, fk_data_mart_table_id) VALUES ('1570777', 'gstin_number', 'gstin_number', '1570309');
INSERT INTO metastore.data_mart_table_schema (id, real_column_name, virtual_name, fk_data_mart_table_id) VALUES ('1570778', 'shipped_date', 'shipped_date', '1570309');
INSERT INTO metastore.data_mart_table_schema (id, real_column_name, virtual_name, fk_data_mart_table_id) VALUES ('1570779', 'delivered_date', 'delivered_date', '1570309');
INSERT INTO metastore.data_mart_table_schema (id, real_column_name, virtual_name, fk_data_mart_table_id) VALUES ('1570780', 'lsp_name', 'lsp_name', '1570309');
INSERT INTO metastore.data_mart_table_schema (id, real_column_name, virtual_name, fk_data_mart_table_id) VALUES ('1570781', 'B_GMV', 'B_GMV', '1570309');
INSERT INTO metastore.data_mart_table_schema (id, real_column_name, virtual_name, fk_data_mart_table_id) VALUES ('1570782', 'sku', 'sku', '1570309');
INSERT INTO metastore.data_mart_table_schema (id, real_column_name, virtual_name, fk_data_mart_table_id) VALUES ('1570735', 'order_date', 'order_date', '1570270');
INSERT INTO metastore.data_mart_table_schema (id, real_column_name, virtual_name, fk_data_mart_table_id) VALUES ('1570736', 'uid', 'order_sku_id', '1570270');
INSERT INTO metastore.data_mart_table_schema (id, real_column_name, virtual_name, fk_data_mart_table_id) VALUES ('1570737', 'order_no_final', 'order_no_final', '1570270');
INSERT INTO metastore.data_mart_table_schema (id, real_column_name, virtual_name, fk_data_mart_table_id) VALUES ('1570738', 'order_id', 'order_id', '1570270');
INSERT INTO metastore.data_mart_table_schema (id, real_column_name, virtual_name, fk_data_mart_table_id) VALUES ('1570739', 'booked_device', 'booked_device', '1570270');
INSERT INTO metastore.data_mart_table_schema (id, real_column_name, virtual_name, fk_data_mart_table_id) VALUES ('1570740', 'order_item_id', 'order_item_id', '1570270');
INSERT INTO metastore.data_mart_table_schema (id, real_column_name, virtual_name, fk_data_mart_table_id) VALUES ('1570741', 'order_status', 'order_status', '1570270');
INSERT INTO metastore.data_mart_table_schema (id, real_column_name, virtual_name, fk_data_mart_table_id) VALUES ('1570742', 'line_status', 'line_status', '1570270');
INSERT INTO metastore.data_mart_table_schema (id, real_column_name, virtual_name, fk_data_mart_table_id) VALUES ('1570743', 'product_title', 'product_title', '1570270');
INSERT INTO metastore.data_mart_table_schema (id, real_column_name, virtual_name, fk_data_mart_table_id) VALUES ('1570744', 'tax_inclusive_price', 'tax_inclusive_price', '1570270');
INSERT INTO metastore.data_mart_table_schema (id, real_column_name, virtual_name, fk_data_mart_table_id) VALUES ('1570745', 'order_quantity', 'order_quantity', '1570270');
INSERT INTO metastore.data_mart_table_schema (id, real_column_name, virtual_name, fk_data_mart_table_id) VALUES ('1570746', 'order_tax', 'order_tax', '1570270');
INSERT INTO metastore.data_mart_table_schema (id, real_column_name, virtual_name, fk_data_mart_table_id) VALUES ('1570747', 'coupoun_discount', 'coupoun_discount', '1570270');
INSERT INTO metastore.data_mart_table_schema (id, real_column_name, virtual_name, fk_data_mart_table_id) VALUES ('1570748', 'total', 'total', '1570270');
INSERT INTO metastore.data_mart_table_schema (id, real_column_name, virtual_name, fk_data_mart_table_id) VALUES ('1570749', 'logical_cp', 'logical_cp', '1570270');
INSERT INTO metastore.data_mart_table_schema (id, real_column_name, virtual_name, fk_data_mart_table_id) VALUES ('1570750', 'total_cp', 'total_cp', '1570270');
INSERT INTO metastore.data_mart_table_schema (id, real_column_name, virtual_name, fk_data_mart_table_id) VALUES ('1570751', 'sku', 'sku', '1570270');
INSERT INTO metastore.data_mart_table_schema (id, real_column_name, virtual_name, fk_data_mart_table_id) VALUES ('1570752', 'payment_mode', 'payment_mode', '1570270');
INSERT INTO metastore.data_mart_table_schema (id, real_column_name, virtual_name, fk_data_mart_table_id) VALUES ('1570753', 'state', 'state', '1570270');
INSERT INTO metastore.data_mart_table_schema (id, real_column_name, virtual_name, fk_data_mart_table_id) VALUES ('1570754', 'city', 'city', '1570270');
INSERT INTO metastore.data_mart_table_schema (id, real_column_name, virtual_name, fk_data_mart_table_id) VALUES ('1570755', 'utm_source', 'utm_source', '1570270');
INSERT INTO metastore.data_mart_table_schema (id, real_column_name, virtual_name, fk_data_mart_table_id) VALUES ('1570756', 'shipping_charge', 'shipping_charge', '1570270');
INSERT INTO metastore.data_mart_table_schema (id, real_column_name, virtual_name, fk_data_mart_table_id) VALUES ('1570757', 'ib_cash_debit', 'ib_cash_debit', '1570270');
INSERT INTO metastore.data_mart_table_schema (id, real_column_name, virtual_name, fk_data_mart_table_id) VALUES ('1570758', 'cod_charge', 'cod_charge', '1570270');
INSERT INTO metastore.data_mart_table_schema (id, real_column_name, virtual_name, fk_data_mart_table_id) VALUES ('1570759', 'bulk_discount', 'bulk_discount', '1570270');
INSERT INTO metastore.data_mart_table_schema (id, real_column_name, virtual_name, fk_data_mart_table_id) VALUES ('1570760', 'utm_campaign', 'utm_campaign', '1570270');
INSERT INTO metastore.data_mart_table_schema (id, real_column_name, virtual_name, fk_data_mart_table_id) VALUES ('1570761', 'utm_medium', 'utm_medium', '1570270');
INSERT INTO metastore.data_mart_table_schema (id, real_column_name, virtual_name, fk_data_mart_table_id) VALUES ('1570762', 'pincode', 'pincode', '1570270');
INSERT INTO metastore.data_mart_table_schema (id, real_column_name, virtual_name, fk_data_mart_table_id) VALUES ('1570763', 'category_env', 'category_env', '1570270');