INSERT INTO schema_store_view (id, name, query, description, materialized_table, generator, fk_organisation_id, fk_schema_store_view_container_id) VALUES ('1570819', 'ORDER_SHIPMENT', ' (select * from my_test_db.orders_order t1 INNER JOIN
my_test_db.order_shipment t2 on t1.order_no_final = t2.order_no)', NULL, NULL, 'query_builder', '1568338', '1570178') using metastore;
INSERT INTO schema_store_view_schema (id, fk_schema_store_view_id, column_name, data_type) VALUES ('1570820', '1570819', 'order_date', 'string') using metastore;
INSERT INTO schema_store_view_schema (id, fk_schema_store_view_id, column_name, data_type) VALUES ('1570821', '1570819', 'uid', 'string') using metastore;
INSERT INTO schema_store_view_schema (id, fk_schema_store_view_id, column_name, data_type) VALUES ('1570822', '1570819', 'order_no_final', 'string') using metastore;
INSERT INTO schema_store_view_schema (id, fk_schema_store_view_id, column_name, data_type) VALUES ('1570823', '1570819', 'order_id', 'string') using metastore;
INSERT INTO schema_store_view_schema (id, fk_schema_store_view_id, column_name, data_type) VALUES ('1570824', '1570819', 'booked_device', 'string') using metastore;
INSERT INTO schema_store_view_schema (id, fk_schema_store_view_id, column_name, data_type) VALUES ('1570825', '1570819', 'order_item_id', 'string') using metastore;
INSERT INTO schema_store_view_schema (id, fk_schema_store_view_id, column_name, data_type) VALUES ('1570826', '1570819', 'order_status', 'string') using metastore;
INSERT INTO schema_store_view_schema (id, fk_schema_store_view_id, column_name, data_type) VALUES ('1570827', '1570819', 'line_status', 'string') using metastore;
INSERT INTO schema_store_view_schema (id, fk_schema_store_view_id, column_name, data_type) VALUES ('1570828', '1570819', 'product_title', 'string') using metastore;
INSERT INTO schema_store_view_schema (id, fk_schema_store_view_id, column_name, data_type) VALUES ('1570829', '1570819', 'tax_inclusive_price', 'string') using metastore;
INSERT INTO schema_store_view_schema (id, fk_schema_store_view_id, column_name, data_type) VALUES ('1570830', '1570819', 'order_quantity', 'string') using metastore;
INSERT INTO schema_store_view_schema (id, fk_schema_store_view_id, column_name, data_type) VALUES ('1570831', '1570819', 'order_tax', 'string') using metastore;
INSERT INTO schema_store_view_schema (id, fk_schema_store_view_id, column_name, data_type) VALUES ('1570832', '1570819', 'coupoun_discount', 'string') using metastore;
INSERT INTO schema_store_view_schema (id, fk_schema_store_view_id, column_name, data_type) VALUES ('1570833', '1570819', 'total', 'string') using metastore;
INSERT INTO schema_store_view_schema (id, fk_schema_store_view_id, column_name, data_type) VALUES ('1570834', '1570819', 'logical_cp', 'string') using metastore;
INSERT INTO schema_store_view_schema (id, fk_schema_store_view_id, column_name, data_type) VALUES ('1570835', '1570819', 'total_cp', 'string') using metastore;
INSERT INTO schema_store_view_schema (id, fk_schema_store_view_id, column_name, data_type) VALUES ('1570836', '1570819', 'sku', 'string') using metastore;
INSERT INTO schema_store_view_schema (id, fk_schema_store_view_id, column_name, data_type) VALUES ('1570837', '1570819', 'payment_mode', 'string') using metastore;
INSERT INTO schema_store_view_schema (id, fk_schema_store_view_id, column_name, data_type) VALUES ('1570838', '1570819', 'state', 'string') using metastore;
INSERT INTO schema_store_view_schema (id, fk_schema_store_view_id, column_name, data_type) VALUES ('1570839', '1570819', 'city', 'string') using metastore;
INSERT INTO schema_store_view_schema (id, fk_schema_store_view_id, column_name, data_type) VALUES ('1570840', '1570819', 'utm_source', 'string') using metastore;
INSERT INTO schema_store_view_schema (id, fk_schema_store_view_id, column_name, data_type) VALUES ('1570841', '1570819', 'shipping_charge', 'string') using metastore;
INSERT INTO schema_store_view_schema (id, fk_schema_store_view_id, column_name, data_type) VALUES ('1570842', '1570819', 'ib_cash_debit', 'string') using metastore;
INSERT INTO schema_store_view_schema (id, fk_schema_store_view_id, column_name, data_type) VALUES ('1570843', '1570819', 'cod_charge', 'string') using metastore;
INSERT INTO schema_store_view_schema (id, fk_schema_store_view_id, column_name, data_type) VALUES ('1570844', '1570819', 'bulk_discount', 'string') using metastore;
INSERT INTO schema_store_view_schema (id, fk_schema_store_view_id, column_name, data_type) VALUES ('1570845', '1570819', 'utm_campaign', 'string') using metastore;
INSERT INTO schema_store_view_schema (id, fk_schema_store_view_id, column_name, data_type) VALUES ('1570846', '1570819', 'utm_medium', 'string') using metastore;
INSERT INTO schema_store_view_schema (id, fk_schema_store_view_id, column_name, data_type) VALUES ('1570847', '1570819', 'pincode', 'string') using metastore;
INSERT INTO schema_store_view_schema (id, fk_schema_store_view_id, column_name, data_type) VALUES ('1570848', '1570819', 'category_env', 'string') using metastore;
INSERT INTO schema_store_view_schema (id, fk_schema_store_view_id, column_name, data_type) VALUES ('1570849', '1570819', 'order_no', 'string') using metastore;
INSERT INTO schema_store_view_schema (id, fk_schema_store_view_id, column_name, data_type) VALUES ('1570850', '1570819', 'tax_exclusive_price', 'string') using metastore;
INSERT INTO schema_store_view_schema (id, fk_schema_store_view_id, column_name, data_type) VALUES ('1570851', '1570819', 'allocation_mode', 'string') using metastore;
INSERT INTO schema_store_view_schema (id, fk_schema_store_view_id, column_name, data_type) VALUES ('1570852', '1570819', 'warehouse_code', 'string') using metastore;
INSERT INTO schema_store_view_schema (id, fk_schema_store_view_id, column_name, data_type) VALUES ('1570853', '1570819', 'order_check_gstin', 'string') using metastore;
INSERT INTO schema_store_view_schema (id, fk_schema_store_view_id, column_name, data_type) VALUES ('1570854', '1570819', 'gstin_number', 'string') using metastore;
INSERT INTO schema_store_view_schema (id, fk_schema_store_view_id, column_name, data_type) VALUES ('1570855', '1570819', 'shipped_date', 'string') using metastore;
INSERT INTO schema_store_view_schema (id, fk_schema_store_view_id, column_name, data_type) VALUES ('1570856', '1570819', 'delivered_date', 'string') using metastore;
INSERT INTO schema_store_view_schema (id, fk_schema_store_view_id, column_name, data_type) VALUES ('1570857', '1570819', 'lsp_name', 'string') using metastore;
INSERT INTO schema_store_view_schema (id, fk_schema_store_view_id, column_name, data_type) VALUES ('1570858', '1570819', 'B_GMV', 'string') using metastore;
INSERT INTO schema_store_view_schema (id, fk_schema_store_view_id, column_name, data_type) VALUES ('1570859', '1570819', 'sku', 'string') using metastore;
INSERT INTO schema_store_view_schema (id, fk_schema_store_view_id, column_name, data_type) VALUES ('15707757', '1570819', 'lsp_name', 'string') using metastore;
INSERT INTO schema_store_view_meta (id, meta_data, fk_schema_store_view_id) VALUES ('dfa7e26b-60b9-42bb-9894-34a8cc60b759', '{"viewName":"order_shipment","tables":[],"selectedItems":[],"groupbyColumns":[],"groupbyRollupColumns":[],"groupbyCubeColumns":[],"predicates":[],"orderbys":[],"havings":[],"emptyItems":[],"columnConnections":[],"tableConnections":[],"tableUi":[],"__type":"Object"}', '1570819') using metastore;