INSERT INTO metastore.pipeline_container (id, name, case_sensitive_name, description, fk_organisation_id) VALUES ('1570872', 'crash_pipeline', 'CRASH_PIPELINE', NULL, '1568338');
INSERT INTO metastore.pipeline_relation (id, name, case_sensitive_name, description, fk_pipeline_container_id) VALUES ('1570930', 'crash_person_collison', 'crash_person_collison', NULL, '1570872');
INSERT INTO metastore.pipeline_node (id, name, case_sensitive_name, description, fk_pipeline_relation_id, pipeline_type, sources) VALUES ('1571084', 'sqltable_crash', 'sqltable_crash', NULL, '1570930', 'SQLTable', NULL);
INSERT INTO metastore.pipeline_node (id, name, case_sensitive_name, description, fk_pipeline_relation_id, pipeline_type, sources) VALUES ('1571115', 'sqltable_person', 'sqltable_person', NULL, '1570930', 'SQLTable', NULL);
INSERT INTO metastore.pipeline_node (id, name, case_sensitive_name, description, fk_pipeline_relation_id, pipeline_type, sources) VALUES ('1571137', 'sqltable_vehicle', 'sqltable_vehicle', NULL, '1570930', 'SQLTable', NULL);
INSERT INTO metastore.pipeline_node (id, name, case_sensitive_name, description, fk_pipeline_relation_id, pipeline_type, sources) VALUES ('1571163', 'join_2', 'join_2', NULL, '1570930', 'JOIN', 'sqltable_crash,sqltable_person,sqltable_vehicle');
INSERT INTO metastore.pipeline_sqltable (id, source_tables, sql_query) VALUES ('1571115', NULL, 'select * from NY_VEHICLE_COLLISIONS.person');
INSERT INTO metastore.pipeline_sqltable (id, source_tables, sql_query) VALUES ('1571084', NULL, 'select * from NY_VEHICLE_COLLISIONS.crash');
INSERT INTO metastore.pipeline_sqltable (id, source_tables, sql_query) VALUES ('1571137', NULL, 'select *
from NY_VEHICLE_COLLISIONS.vehicle');
INSERT INTO metastore.pipeline_join (id, join_tables, join_predicate, filter_expression, order_by) VALUES ('1571163', 'sqltable_crash,sqltable_person,sqltable_vehicle', '(sqltable_crash.collision_id(+) = sqltable_person.collision_id) AND (sqltable_crash.collision_id(+) = sqltable_vehicle.collision_id)', NULL, NULL);
INSERT INTO metastore.pipeline_coordinates (id, coordinates, fk_pipeline_relation_id) VALUES ('4b5fbadd-48cc-4b8e-bb52-1202478f78e0', '{"positions":[{"name":"sqltable_crash","type":"SQLTable","xCord":"34px","yCord":"80px","isExpand":null},{"name":"sqltable_person","type":"SQLTable","xCord":"30px","yCord":"201px","isExpand":null},{"name":"join_2","type":"Join","xCord":"264px","yCord":"130px","isExpand":null},{"name":"sqltable_vehicle","type":"SQLTable","xCord":"9px","yCord":"326px","isExpand":null}],"connections":[{"source":"sqltable_crash","target":"join_2","targetType":0},{"source":"sqltable_person","target":"join_2","targetType":0},{"source":"sqltable_vehicle","target":"join_2","targetType":0}]}', '1570930');